### ISSUE TITLE
Bug: unmarshal error for `redirect_uris` in `authentik_provider_oauth2` and `authentik_provider_proxy`

### ISSUE THREAD

**Issue by martinohmann** [goauthentik/terraform-provider-authentik#595]
Hi there!

After I upgraded authentik from 2024.10.2 to 2024.10.4 the `authentik_provider_oauth2` and `authentik_provider_proxy` resources produce JSON unmarshal errors due to a type mismatch of the `redirect_uris` field.

I looked though the authentik changelog and it seems like the terraform provider needs to be adapted to the changes from https://github.com/goauthentik/authentik/commit/fabacc56c420a597b49ef06432690e1d278db890.

## Error in `authentik_provider_oauth2`

```
│ Error: HTTP Error 'json: cannot unmarshal array into Go struct field OAuth2Provider.redirect_uris of type string' during request 'GET /api/v3/providers/oauth2/5/': "{"pk":5,"name":"MinIO","authentication_flow":null,"authorization_flow":"cc3ef0ff-b661-401e-bd62-fb3152a460da","invalidation_flow":"a1f16bd3-8682-4df2-b1e7-42589b5ce2fe","property_mappings":["9c7f791f-3469-4b27-84d5-ae8977a3207a","1246b098-28ed-4e42-8159-94cb8135d8c0","09c5cecd-8e89-4d87-8bc0-82c7509a5c72","7e14d1c9-3a01-40ac-8f1e-06fbee22ef77"],"component":"ak-provider-oauth2-form","assigned_application_slug":"minio","assigned_application_name":"MinIO","verbose_name":"OAuth2/OpenID Provider","verbose_name_plural":"OAuth2/OpenID Providers","meta_model_name":"authentik_providers_oauth2.oauth2provider","client_type":"confidential","client_id":"[...REDACTED...]","client_secret":"[...REDACTED...]","access_code_validity":"hours=24","access_token_validity":"minutes=10","refresh_token_validity":"days=30","include_claims_in_id_token":true,"signing_key":"a1305537-5e31-4d30-8485-33a47e1bcae7","encryption_key":null,"redirect_uris":[{"matching_mode":"strict","url":"https://minio.mydomain.tld/oauth_callback"}],"sub_mode":"hashed_user_id","issuer_mode":"per_provider","jwks_sources":[]}"
│
│   with module.oauth2-minio.authentik_provider_oauth2.oauth2-application,
│   on modules/oauth2-application/main.tf line 13, in resource "authentik_provider_oauth2" "oauth2-application":
│   13: resource "authentik_provider_oauth2" "oauth2-application" {
│
╵
```

## Error in  `authentik_provider_proxy` resource

```
│ Error: HTTP Error 'json: cannot unmarshal array into Go struct field ProxyProvider.redirect_uris of type string' during request 'GET /api/v3/providers/proxy/48/': "{"pk":48,"name":"Filebrowser","authentication_flow":null,"authorization_flow":"cc3ef0ff-b661-401e-bd62-fb3152a460da","invalidation_flow":"a1f16bd3-8682-4df2-b1e7-42589b5ce2fe","property_mappings":["7b7ee412-4811-40cf-af21-4020c24e81a4","1246b098-28ed-4e42-8159-94cb8135d8c0","09c5cecd-8e89-4d87-8bc0-82c7509a5c72","7e14d1c9-3a01-40ac-8f1e-06fbee22ef77"],"component":"ak-provider-proxy-form","assigned_application_slug":"filebrowser","assigned_application_name":"Filebrowser","verbose_name":"Proxy Provider","verbose_name_plural":"Proxy Providers","meta_model_name":"authentik_providers_proxy.proxyprovider","client_id":"[...REDACTED...]","internal_host":"","external_host":"https://filebrowser.mydomain.tld","internal_host_ssl_validation":true,"certificate":null,"skip_path_regex":"","basic_auth_enabled":false,"basic_auth_password_attribute":"","basic_auth_user_attribute":"","mode":"forward_single","intercept_header_auth":true,"redirect_uris":[{"matching_mode":"strict","url":"https://filebrowser.mydomain.tld/outpost.goauthentik.io/callback?X-authentik-auth-callback=true"},{"matching_mode":"strict","url":"https://filebrowser.mydomain.tld?X-authentik-auth-callback=true"}],"cookie_domain":"","jwks_sources":[],"access_token_validity":"hours=24","refresh_token_validity":"days=30","outpost_set":["Outpost storage-proxy"]}"
│
│   with module.proxy-filebrowser.authentik_provider_proxy.proxy_provider,
│   on modules/proxy-application/main.tf line 1, in resource "authentik_provider_proxy" "proxy_provider":
│    1: resource "authentik_provider_proxy" "proxy_provider" {
│
```

## Versions

authentik: 2024.10.4
terraform-provider-authentik: 2024.10.1

Let me know if you need more details.

**Comment by ShockStricken** [comment]
I'm seeing the exact issue, commenting to increase awareness.

**Comment by BeryJu** [comment]
This is fixed by https://github.com/goauthentik/terraform-provider-authentik/pull/593, which will be available with 2024.10.2 of the terraform provider shortly

**Comment by alexppg** [comment]
I'm still encountering this issue, could we please reopen it? 

![imagen](https://github.com/user-attachments/assets/a377fe93-b560-451c-85ad-9adbaa0dc810)
